baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Future App'
logo: "assets/images/logo.png"
address: "Ahmedabad, Gujarat, 382481"
call-chat:
  enable: true
  items:
    - icon: "fa fa-phone-square"
      title: "+91 9601412598"
      link: "tel:+919601412598"
    - icon: "fab fa-whatsapp"
      title: "+91 9601412598"
      link: "https://wa.me/919601412598"
social:
  enable: false
  items:
  - icon: "fab  fa-facebook-square"
    title: "facebook"
    link: ""
  - icon: "fab fa-twitter-square"
    title: "twitter"
    link: ""
apps:
  enable: true
  items:
  - link: "https://play.google.com/store/apps/details?id=com.future.core" 
    icon: "/assets/images/google-play.png"
    title: "google play"

email: "sales@futureapp.in"


markdown: kramdown

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

# Your disqus shortname, entering this will enable commenting on posts
disqus: ""

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: ""

home:
  top-bar: 
    enabled: true
    left: #<strong><a href='#' >Now Hiring:</a></strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed.
    right: 
    - icon: "fa fa-phone"
      title: "<strong>+91 9601412598</strong>"
      link: "tel:+919601412598"
    - icon: "fa fa-map-marker-alt"
      title: "Ahmedabad, Gujarat, 382481"
      link: 
  hero:
    image: "assets/images/banner.jpg"
    title:
    button:
    - text:
      url:
      image:
    - text:
      url:
      image:
  about:
    enabled: true
    heading: "About Us"
    subHeading: "Connecting schools and  parents via technology to make your <span>child's future</span>"
    text: "<p>FutureApp allows parents to stay updated about their kids progress. At the same time it helps school management to make routine work automated and easy</p>"
    image: "assets/images/about.png"
    videoUrl: "https://www.youtube.com/embed/pcj1XNnABak" 
  approch:
    enabled: false
    heading: "approch"
    smallHeading: 
    info: 
    - title: TRADITIONAL APPROACH
      icon: "assets/images/arrow.png"
      image:  "assets/images/traditional.png"
      text: "FutureApp allows parents to stay <br> updated about their kids progress."
    - title: future app AI
      icon: "assets/images/blub.png"
      image: "assets/images/school-way.png"
      text: "At the same time it helps school management <br> to make routine work automated and easy"
  counter:
    enabled: true
    title: "Counter"
    image: "assets/images/counter-bg.jpg"
    lists:
    - icon: "assets/images/online-class.png"
      number: 3000 
      afternumber: "+"
      title: "Online Classes Conducted"
    - icon: "assets/images/school.png"
      number: 200
      afternumber: "+"
      title: Happy School 
    - icon: "assets/images/satisfaction.png"
      number: 99
      afternumber: "%"
      title: Customer Satiscfaction
    - icon: "assets/images/review.png"
      number: 1000
      afternumber: "+"
      title: Google Reviews
  ecosystem:
    enabled: true
    title: "The Ecosystem of Apps"
  control:
    enabled: false
    title: "Take control of your school online"
  testimonials:
    enabled: true
    title: "What do people praise about  <span>FutureApp?</span>"
    badgeTitle: "Testimonials"
  clients:
    enabled: true
    title: "We see our success in your client <span>satisfaction</span>."
    badgeTitle: "Our Clients"
  contact:
    enabled: true
    title: "We'd love to hear from you"
    badgeTitle: "Get IN Touch"
  help:
    enabled: false
    title: "Help whenever you need it"
    badgeTitle: "Help"
    info: "Our support team is available 24/7 via live chat, phone and email. Whether you need help updating your menu,<br> want to run a new marketing campaign or have a product question, we’re always here to help."
    image: "assets/images/help.png"

  
    
footer:
  logo: "assets/images/white-logo.png"
  copyright: All Rights Reserved
  leftcolHeading: 
  centercolHeading:  "Useful Links"
  rightcolHeading: "We're Hiring I!"
  leftcol:
  - link: "/privacy-policy/"
    text: Privacy Policy
  centercol:  
  - text: Home                                             
    link: "#home"
    weight: 1
    pageType: "same"
  - text: How its Works
    link: "#how-its-works"
    pageType: "same"
    weight: 2
  - text: About Us
    link: "#about"
    pageType: "same"
    weight: 3
  rightcol:
    text: We’re more interested in you. let's grow together
    btntext: "Register Now" 
    btnurl: "#contact" 



# Use the following plug-ins
gems:
- jekyll-sitemap
- jekyll-paginate



# Exclude these files from your production _site
exclude:
  - Gemfile.lock
  - LICENSE
  - README.md
