baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Future App'
logo: "assets/images/logo.png"
address: "Ahmedabad, Gujarat, 382481"
phone: "+91 9601412598"
email: "sales@futureapp.in"
social:
- icon: "fab  fa-facebook-square"
  title: "facebook"
  link: "sales@futureapp.in"
- icon: "fab fa-twitter-square"
  title: "twitter"
  link: "sales@futureapp.in"
// - icon: "fab fa-skype"
//   title: "skype"
//   link: "thesiliconvalleyacademy@gmail.com"
apps:
- link: "https://play.google.com/store/apps/details?id=com.future.core" 
  icon: "/assets/images/googleplay-white.jpg"
  title: "google play"


markdown: kramdown

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

# Your disqus shortname, entering this will enable commenting on posts
disqus: ""

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: ""

home:
  top-bar: 
    enabled: true
    left: #<strong><a href='#' >Now Hiring:</a></strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed.
    right: 
    - icon: "fa fa-phone"
      title: "<strong>0122 8899900</strong>"
      link: "tel:01228899900"
    - icon: "fa fa-map-marker-alt"
      title: "Ahmedabad, Gujarat, 382481"
      link: 
  hero:
    image: "assets/images/banner.jpg"
    title:
    button:
    - text:
      url:
      image:
    - text:
      url:
      image:
  about:
    enabled: true
    heading: "About Us"
    subHeading: "Connecting schools and  parents via technology to make your <span>child's future</span>"
    text: "<p>FutureApp allows parents to stay updated about their kids progress. At the same time it helps school management to make routine work automated and easy</p>"
    image: "assets/images/about.png"
    videoUrl: "https://www.youtube.com/embed/pcj1XNnABak" 
  approch:
    enabled: true
    heading: "approch"
    smallHeading: 
    info: 
    - title: TRADITIONAL APPROACH
      icon: "assets/images/arrow.png"
      image:  "assets/images/traditional.png"
      text: "FutureApp allows parents to stay <br> updated about their kids progress."
    - title: future app AI
      icon: "assets/images/blub.png"
      image: "assets/images/school-way.png"
      text: "At the same time it helps school management <br> to make routine work automated and easy"
  counter:
    enabled: true
    title: "Counter"
    image: "assets/images/counter-bg.jpg"
    lists:
    - icon: "assets/images/scucceful.png"
      number: 20 
      afternumber: "+"
      title: Successful Years
    - icon: "assets/images/happy.png"
      number: 1300
      afternumber: "+"
      title: Happy Clients
    - icon: "assets/images/satisfaction.png"
      number: 99
      afternumber: "%"
      title: Customer Satiscfaction
    - icon: "assets/images/review.png"
      number: 1000
      afternumber: "+"
      title: Google Reviews
  ecosystem:
    enabled: true
    title: "The Ecosystem of Apps"
  control:
    enabled: false
    title: "Take control of your school online"
  testimonials:
    enabled: true
    title: "What do people praise about  <span>FutureApp?</span>"
    badgeTitle: "Testimonials"
  clients:
    enabled: true
    title: "We see our success in your client <span>satisfaction</span>."
    badgeTitle: "Our Clients"
  contact:
    enabled: true
    title: "We'd love to hear from you"
    badgeTitle: "Get IN Touch"
  help:
    enabled: true
    title: "Help whenever you need it"
    badgeTitle: "Help"
    info: "Our support team is available 24/7 via live chat, phone and email. Whether you need help updating your menu,<br> want to run a new marketing campaign or have a product question, we’re always here to help."
    image: "assets/images/help.png"

  
    
footer:
  logo: "assets/images/white-logo.png"
  copyright: All Rights Reserved
  leftcolHeading: 
  centercolHeading:  "Useful Links"
  rightcolHeading: "We're Hiring I!"
  leftcol:
  - link: "#"
    text: Terms of Use
  - link: "#"
    text: Privacy Policy
  centercol:
  - link: "#"
    text: Why us
  - link: "#"
    text: How it works
  - link: "#"
    text: About US 
  - link: "#"
    text: Contact Us
  - link: "#"
    text: Pricing
  rightcol:
    text: We’re more interested in you. let's grow together
    btntext: "Register Now" 
    btnurl: "#" 



# Use the following plug-ins
gems:
- jekyll-sitemap
- jekyll-paginate



# Exclude these files from your production _site
exclude:
  - Gemfile.lock
  - LICENSE
  - README.md
